# Generated by Django 4.2.1 on 2023-05-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signupbanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_text', models.CharField(max_length=1000)),
                ('small_text', models.TextField()),
                ('signuppicture', models.ImageField(upload_to='signupbannerpicture/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
