# Generated by Django 4.2.1 on 2023-05-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_southafricaupdate_southafricaupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tracking_number', models.TextField(max_length=100)),
            ],
        ),
    ]
