# Generated by Django 4.2.1 on 2023-05-30 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_trackingnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=50)),
                ('types_of_shipment', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=7)),
                ('packages', models.CharField(max_length=3)),
                ('product', models.CharField(max_length=3)),
                ('payment_mode', models.CharField(max_length=20)),
                ('carrier', models.CharField(max_length=100)),
                ('departure_time', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('pickup_time', models.CharField(max_length=20)),
                ('courier', models.CharField(max_length=50)),
                ('tracking_number', models.CharField(max_length=10)),
                ('origin', models.CharField(max_length=50)),
                ('pickup_date', models.CharField(max_length=20)),
                ('expected_delivery_date', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipperDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('shipmentDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.shipmentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='receiverDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('shipmentDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.shipmentdetails')),
            ],
        ),
    ]
