# Generated by Django 4.2.1 on 2023-05-31 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_shipmentdetails_shipperdetails_receiverdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmentdetails',
            old_name='carrier',
            new_name='current_location',
        ),
    ]
