# Generated by Django 4.2.1 on 2023-05-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_bannerpictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpictures',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
